[cluster]
name = "blah"

[[nodes]]
clientBindAddress = "127.0.0.1"
clientBindPort = 6453
rpcBindAddress = "127.0.0.1"
rpcBindPort = 56453

[[nodes]]
clientBindAddress = "127.0.0.1"
clientBindPort = 6454
rpcBindAddress = "127.0.0.1"
rpcBindPort = 56454

[driver]
name = "sqlite"
